\pset pager off
\pset footer off
\qecho ' '
\qecho ' '

\qecho '==SNAPSHOT DETAILS=='
\qecho ' '
\qecho 'list_snaps.sql                      			List snapshots available with time window'
\qecho ' '
\qecho ' '

\qecho '==SET SNAPSHOT WINDOW=='
\qecho ' '
\qecho 'set_snaps.sql                                          Set Begin and End Snapshot ID for Analysis'
\qecho ' '
\qecho ' '


\qecho '==INSTANCE AND DATABASE STATS=='
\qecho ' '
\qecho 'db_and_schema_sizes.sql                 		Database and Schema Sizes'
\qecho 'top_20_tables_and_indexes_by_tot_size.sql   		Top 20 Tables and Indexes by total Size'
\qecho 'cache_hit_ratio.sql                 			Cache hit ratio in a time window'
\qecho 'db_stats.sql                         			Database Level statistics in a time window'
\qecho ' '
\qecho ' '

\qecho '==SESSION STATS=='
\qecho ' '
\qecho 'session_cnt.sql                      			Total Sessions and Session count by state in a time window'
\qecho 'session_activity_hist.sql           			Sessions activity with wait events in a time window'
\qecho 'blockers_and_waiters_hist.sql       			Blocking and Waiting Sessions in a time window'
\qecho 'vacuum_history.sql                  			Vacuum activity in a time window'
\qecho ' '
\qecho ' '

\qecho '==SQL STATS=='
\qecho ' '
\qecho 'top_20_sqls_by_calls.sql               			Top 20 queries by Executions/Calls in a time window'
\qecho 'top_20_sqls_by_elapsed_time.sql        			Top 20 queries by Elapsed time in a time window'
\qecho 'sql_stat_history.sql                			Execution trend of a query of interest in a time window'
\qecho ' '
\qecho ' '

\qecho '==TABLE STATS=='
\qecho ' '
\qecho 'top_20_tables_by_seq_scans.sql      			Top 20 Tables by number of Sequential or Full scans'
\qecho 'top_20_tables_by_dmls.sql           			Top 20 Tables by DML activity'
\qecho ' '
\qecho ' '

\qecho '==INDEX STATS=='
\qecho ' '
\qecho 'indexes_on_table.sql                			Indexes on a table'
\qecho 'top_20_indexes_by_scans.sql         			Top 20 Indexes by number of Scans initiated in the index'
\qecho 'top_20_indexes_by_avg_tuple_reads.sql       		TOP 20 Indexes by average Tuples Reads/Scan'
\qecho 'unused_indexes.sql                  			Unused Indexes'
\qecho ' '
\qecho ' '
